// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patient_Monitoring.Data;

#nullable disable

namespace Patient_Monitoring.Migrations
{
    [DbContext(typeof(PatientMonitoringDbContext))]
    partial class PatientMonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patient_Monitoring.Models.Appointment", b =>
                {
                    b.Property<string>("AppointmentID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Appointment_Date_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Appointment_Alert", b =>
                {
                    b.Property<string>("AlertID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppointmentID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlertID");

                    b.ToTable("Appointment_Alerts");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Disease", b =>
                {
                    b.Property<string>("DiseaseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Doctor_Detail", b =>
                {
                    b.Property<string>("DoctorID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctor_Details");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Detail", b =>
                {
                    b.Property<string>("PatientID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.ToTable("Patient_Details");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Diagnosis", b =>
                {
                    b.Property<string>("DiagnosisID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiseaseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DiagnosisID");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PatientID");

                    b.ToTable("Patient_Diagnoses");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Doctor_Mapper", b =>
                {
                    b.Property<string>("PatientID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PatientID");

                    b.ToTable("Patient_Doctor_Mapper");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Medication", b =>
                {
                    b.Property<string>("MedicationID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrescribingDoctorId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("MedicationID");

                    b.ToTable("Patient_Medications");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Plan_Mapper", b =>
                {
                    b.Property<string>("AssignmentID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wellness_PlanPlanID")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("Wellness_PlanPlanID");

                    b.ToTable("Patient_Plan_Mapper");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Wellness_Plan", b =>
                {
                    b.Property<string>("PlanID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Frequency_Count")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency_Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Recommended_Duration")
                        .HasColumnType("int");

                    b.Property<bool>("is_custom")
                        .HasColumnType("bit");

                    b.HasKey("PlanID");

                    b.ToTable("Wellness_Plans");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Appointment", b =>
                {
                    b.HasOne("Patient_Monitoring.Models.Doctor_Detail", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Diagnosis", b =>
                {
                    b.HasOne("Patient_Monitoring.Models.Appointment", "Appointment")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient_Monitoring.Models.Disease", "Disease")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient_Monitoring.Models.Patient_Detail", "Patient")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Disease");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Plan_Mapper", b =>
                {
                    b.HasOne("Patient_Monitoring.Models.Wellness_Plan", null)
                        .WithMany("AssignedPatients")
                        .HasForeignKey("Wellness_PlanPlanID");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Appointment", b =>
                {
                    b.Navigation("PatientDiagnoses");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Disease", b =>
                {
                    b.Navigation("PatientDiagnoses");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Doctor_Detail", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Patient_Detail", b =>
                {
                    b.Navigation("PatientDiagnoses");
                });

            modelBuilder.Entity("Patient_Monitoring.Models.Wellness_Plan", b =>
                {
                    b.Navigation("AssignedPatients");
                });
#pragma warning restore 612, 618
        }
    }
}
